istio/cni

README.md
from Tim and update test for IKS
=> add instruction on iptables

deployments/kubernetes/install/helm/.helmignore, deployments/kubernetes/install/helm/Chart.yaml, deployments/kubernetes/install/helm/templates/_labels.tpl, deployments/kubernetes/install/helm/templates/istio-cni.yaml, deployments/kubernetes/install/helm/values.yaml, deployments/kubernetes/install/helm/values_gke.yaml
Create the helm chart for the istio-cni deployment with default values.yaml and GKE settings in values_gke.yaml.  
Closes: #4
=> Add helm chart

deployments/kubernetes/install/scripts/install-cni.sh
This PR creates a variable named `MOUNTED_CNI_NET_DIR` to refer to the `/host/etc/cni/net.d` path in the installation script.
Signed-off-by: Venil Noronha <veniln@vmware.com>
=> Extract CNI config mount dir to a variable

deployments/kubernetes/Dockerfile.install-cni, deployments/kubernetes/install/scripts/filter.jq, deployments/kubernetes/install/scripts/install-cni.sh, tools/istio-cni-docker.mk
=> Fix CNI config insertion on files that don't contain .plugins[]

deployments/kubernetes/Dockerfile.install-cni, deployments/kubernetes/install/helm/templates/istio-cni.yaml, deployments/kubernetes/install/scripts/install-cni.sh
- Remove istio-cni plugin config from config chain.
- remove kubeconfig file
Closes: #10
=> istio-cni-node add exit signal handler to clean config

README.md
Show how to use helm to generate a manifest and explain options.  Indicate currently available `values.yaml` files.
=> Update README with helm info

.circleci/config.yml
Trying to see if ci starts running.
=> Merge build+lint

README.md, test/README.md
This README describes the CNI tests and
the specific procedure to run the e2e
tests.
=> Instructions on how to run the Istio e2e

cmd/istio-cni/main.go, tools/deb/istio-iptables.sh
Return error if iptables fails to populate
Fix #23
Fix lock collistion
Signed-off-by: Baodong (Robert) Li <baoli@cisco.com>
=> Add wait and retry logic for iptables call

README.md
update the readme to reflect latest install via Istio helm, troubleshooting info, etc.  General cleanup.
=> Fix up and reorganize README

deployments/kubernetes/install/scripts/install-cni.sh
=> Look for .conflist file if .conf doesn't exist

cmd/istio-cni/main_test.go, cmd/istio-cni/redirect.go, tools/deb/istio-iptables.sh
Cherry-pick #90 into master
- we're wanting to rebase release-1.1 on master since all deltas are compatible fixes for istio release-1.1
=> add kubevirtInterfaces to istio CNI

deployments/kubernetes/Dockerfile.install-cni
Fixes: istio/istio#14320
Signed-off-by: Romain Lenglet <rlenglet@google.com>
=> Move Dockerfile to Ubuntu Xenial and fix linter issues

CODEOWNERS
Romain has been contributing for a bit... make him an owner
=> Add rlenglet to codeowners

deployments/kubernetes/install/helm/istio-cni/values_gke.yaml
Fixes: https://github.com/istio/istio/issues/14805
=> Use consistent image tag in Helm values

deployments/kubernetes/install/helm/istio-cni/values_gke.yaml
Fixes: https://github.com/istio/istio/issues/14805
=> Backport #122 "Use consistent image tag in Helm values"

deployments/kubernetes/install/helm/istio-cni/values.yaml, deployments/kubernetes/install/helm/istio-cni/values_gke.yaml
Keep consistent with istio/istio, cf. https://github.com/istio/istio/pull/14813
=> Update default tag in Helm charts for 1.2

cmd/istio-cni/iptables.go, cmd/istio-cni/main.go, cmd/istio-cni/redirect.go
Introducing Tables interface and making iptables to be compliant with this interface. 
/cc @tiswanso @john-a-joyce
=> Tables interface

Makefile, cmd/istio-cni/intercept_rule_mgr.go, cmd/istio-cni/main.go, cmd/istio-cni/main_test.go, cmd/istio-cni/redirect.go
- default is the existing iptables intercept type
- misc. fix to makefile for precommit target
=> Add plugin config option to select InterceptRuleMgr type

.circleci/config.yml
Also, use latest istio/istio master test cases for IPv6
=> circleci: pin KDC version

tools/packaging/common/iptables-retry.diff, tools/packaging/common/istio-iptables.sh
```
make -f tools/istio-cni-docker.mk update-istio-iptables.sh
```
This PR prepares for the Istio 1.3 release.
=> Update istio-iptables.sh in master

tools/packaging/common/iptables-retry.diff, tools/packaging/common/istio-iptables.sh
Fixes https://github.com/istio/istio/issues/15895
=> Disable retrying ip6tables cleanup when IPv6 is disabled

README.md, deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml, deployments/kubernetes/install/helm/istio-cni/values.yaml
Backport of: https://github.com/istio/installer/pull/396
=> Add the possibility to create RoleBinding for PSP

Makefile.core.mk, test/prow-e2e.sh, tools/istio-cni-docker.mk
Enable CNI test cases for build-tools container within prow's CI.
=> Enable build-tools within CNI repository

test/e2e.sh
This PR needs a careful look at the HUB.  I think we are transitioning
to gcr.io/istio-testing
=> Record logs from e2e tests in event of failure

README.md
It should probably be explained at least once in the README.
=> Expand "CNI" initialism in README

README.md, cmd/istio-cni/kubernetes.go, cmd/istio-cni/main.go, cmd/istio-cni/main_test.go
Issue: https://github.com/istio/istio/issues/18021
=> Exclude pod if istio-init container is present

cmd/istio-cni/main.go
Fixes: https://github.com/istio/istio/issues/17583
Add a simple wait loop to wait until the pod's info is available from
k8s API. Return the k8s error if it fails eventually.
=> Return an error upon fail to obtain pod info

tools/packaging/common/istio-iptables.sh
This is sync from https://github.com/istio/istio/pull/19496
=> Donot redirect app calls back to itself by podip via envoy

Makefile.core.mk, README.md, cmd/istio-cni/main.go, cmd/istio-cni/main_test.go, deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml, deployments/kubernetes/install/helm/istio-cni/values.yaml, deployments/kubernetes/install/scripts/install-cni.sh
Addresses https://github.com/istio/istio/issues/20202
=> Add ability to deploy config file standalone (not chained)

deployments/kubernetes/install/scripts/install-cni.sh
Fixes https://github.com/istio/istio/issues/20044
=> #20044 Adding graceful exit trap to install-cni.sh

tools/packaging/common/istio-iptables.sh
iptable bash version of https://github.com/istio/istio/pull/22686
Signed-off-by: Yuchen Dai <silentdai@gmail.com>
=> inbound port carries all inbound traffic

cmd/istio-cni/kubernetes.go, cmd/istio-cni/main.go, cmd/istio-cni/main_test.go, cmd/istio-cni/redirect.go
InboundPorts annotation set to star only if user doesn't provide label
Use user original value otherwise.
Signed-off-by: Yuchen Dai <silentdai@gmail.com>
Fix up according to #284
=> align iptables args with non-cni
