deployments/kubernetes/install/scripts/install-cni.sh
If '.plugins[]' is not found in original file, jq fails to patch it.
=> The plugins section is optional

deployments/kubernetes/install/scripts/install-cni.sh
For now, name the generated kubeconf file "ZZZ-istio-cni-kubeconfig".
Also, fix command to find first file in cni-conf-dir.
Closes: #12
=> Install: ensure generated kubeconfig file is not the first file in cni-conf-dir

Makefile, README.md
This PR updates `ISTIO_CNI_RELPATH` to `istio.io/cni` in order to enforce a standard location for the Istio CNI plugin.
Fixes #16.
Signed-off-by: Venil Noronha <veniln@vmware.com>
=> Update check-tree path matching

.circleci/config.yml, tools/istio-cni-docker.mk
~depends on PR #24 .  Will rebase this once #24 merges.~  Runs test merged with PR #24 
Runs `make test` in a circleci job in a VM to be able to do the `docker run`.
=> Create circleci job for install-cni test

.circleci/config.yml, cmd/istio-cni/main.go, cmd/istio-cni/main_test.go
Fix k8sArgs elements to exactly match the kubelet key value pairs in the arg string so unmarshalling works.
- add a test case for checking unmarshalling with a sample kubelet arg string
- Add check for sidecar inject disable annotation to not do redirect (set by Istio control-plane pods)
- Changes to .circleci/config.yaml match istio/istio for setting up go 1.10 in the VM
Signed-off-by: Tim Swanson <tiswanso@cisco.com>
Closes: #35
=> fix k8sArgs & make circleci use go 1.10

.circleci/config.yml, OWNERS, deployments/kubernetes/install/helm/istio-cni/Chart.yaml
Once this completes, I'll update the image references to point to istionightly.
I think we can combine lint/build in a single circleci job - in istio/istio things are super slow and need to be in parallel, hopefully we'll not end up in the same state in this repo.
=> Adding nightly

.circleci/config.yml
The nightly is having a problem with the working dir and GOPATH for the make build step.  Fix is to attach the workspace at the right location.
=> Attach the workspace to the /Users/tiswanso/go-istio

.circleci/config.yml
The yaml macros for the nightly job's env settings were getting clobbered by the subsequent use of the "environment:" key containing the TAG setting.  Yaml doesn't do an auto-merge of dicts/maps :-)
Changed to put the tag setting in each command-line for now to make it clear.
**Troubleshooting note:**  use the circleci "configuration" tab on the job view to see the resulting yaml that circleci sees--it has the result of using all those yaml inline macros (references/aliases).
=> circleci: fix nightly job clobber of the build/test env settings

cmd/istio-cni/main.go, cmd/istio-cni/main_test.go, cmd/istio-cni/redirect.go
If annotation keys `traffic.sidecar.*` are present on the pod, use their values as params. 
~TODO--validate values in annotations~ Done
Closes: #42
=> Map pod annotation data to redirect params

.circleci/Dockerfile, .circleci/config.yml, .circleci/run_e2e.sh
CircleCI with k8s on DinD similar to KDC repo--https://github.com/kubernetes-sigs/kubeadm-dind-cluster
1. use circleci remote_docker in the same pattern as KDC's circleci jobs to install a multi-node k8s cluster with flannel CNI.
1. save/restore install-cni docker image under-test from build job.  Copy images into each k8s node's docker cache
1. build a container with Istio master to run Istio e2e tests from the same docker network space as the DinD k8s' kube-master container ("node").  see run_e2e.sh
1. run e2e_simple tests with Istio CNI enabled
1.  collect and copy out k8s state to circleci artifacts
=> CircleCI DinD job

.circleci/config.yml
change it from running every hour on the half past mark.  Only run it nightly at 09:45:00 UTC to try to ensure it picks up Istio's nightly release for testing--istio nightly seems to run at ~09:15 UTC.
Also include the DinD e2e test in the nightly run.
=> Run nightly only at 09:45am UTC and include e2e test

.circleci/Dockerfile, .circleci/config.yml, .circleci/run_e2e.sh
Add a e2e DinD job for testing with Istio release 1.1.
- Build e2e_runner with istio release1.1 content
- trigger e2e with Istio release1.1 nightly images
=> CircleCI e2e test against Istio release1.1 branch

tools/istio-cni-docker.mk
This is needed by the release scripts to save the docker files so that the licenses can be added before pushing.
=> Add docker.save make target

README.md, bin/get_workspace_status.sh, deployments/kubernetes/Dockerfile.install-cni, test/install_k8s_test.go
leaving the references in the helm defaults (values.yaml) since we don't yet have a process that pushes to gcr.io/istio-release yet.
=> Fix build info and other references to user tiswanso in misc places.

cmd/istio-cni/main.go
Fix typo in comment: "plugin-specifc" to "plugin-specific" in line 73.
=> Fix typo in comment

cmd/istio-cni/main.go, cmd/istio-cni/main_test.go, cmd/istio-cni/redirect.go
Hello,
We had a scenario in our cluster were a pod got IP Rules when it did not have the sidecar, to prevent this I have added a check to make sure that the pod has a status annotation, which will only be present if there is a sidecar.
Feedback Welcome!
Thank You
=> Check for Sidecar Annotation Before Redirect

deployments/kubernetes/install/helm/istio-cni/values.yaml, test/README.md
Nightly images are available on gcr.io/istio-release
point to that as the default.
=> Point hub and tag to istio-release

deployments/kubernetes/install/scripts/install-cni.sh, deployments/kubernetes/install/test/install_cni.go
Modify istio-cni-node daemonset's install-cni.sh to periodically check for
- removed istio-cni content from plugins list
- removal of CNI config file
- adding of CNI config file that supersedes the on with istio-cni content
(lexicographically first file)
If found, exit the proc with error so k8s will restart the pod and the
istio-cni install logic will reapply the config.
Fixes: #82
=> Detect clobbering of istio-cni content in CNI conf file

README.md, test/README.md
This change updates the usage section now that the
CNI and Istio charts have been fully decoupled and
a 2 step install process is required. It also updates
the e2e test procedure that also changed due to the
2 step install.
=> Updates the usage section based on 2 step install

deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
In cases where the configuration is not in the default location the
changes the install script makes to existing cni config (such as calico)
point calico's "downstream" config to the wrong place. This should fix
that.
=> Add environment variable for cni configuration location.

.circleci/config.yml
Currently nightly will try to push to docker.io/istio if the DOCKER_USER is set.  Change to push to the DOCKER_USER container registry account and push with container tags based on git tags.   
NOTE: The circleci project settings are what controls DOCKER_USER and DOCKER_PASS.
=> make nightly build and push to docker.io/istiocni for master and 1.1

.mergify.yml
This prevents Mergify from merging a PR before all CircleCI jobs have succeeded.
=> Add all CircleCI jobs as preconditions to Mergify success

.circleci/config.yml, .circleci/run_e2e.sh, tools/deb/istio-iptables.sh
Adds tests using circleCI KDC bringup in ipv6 mode and IPv6 e2e-simple testcase fixes in istio/istio#13753
- istio-iptables.sh changes are identical to istio/istio master with the addition of the ip6tables function to retry on failure to handle potential concurrent ip6tables locking on the same node.
=> Incorporate IPv6 changes from istio/istio 11916

cmd/istio-cni/redirect.go
Currently inbound ports can be excluded from redirection, and outbound IP addresses can be excluded from redirection, but not outbound ports. This fills out the support for that, by adding an traffic.sidecar.istio.io/excludeOutboundPorts annotation.
Istio has the ability to exclude outbound ports by merging #13970 pull request, and this  currently PR is adding the exclude outbound ports to istio cni as well
=> excludeOutboundPorts to facilitate headless data stores

.circleci/config.yml, .mergify.yml
- add release-1.2 branch to circleci nightly workflow runs
- add a job to test against Istio release-1.2 to `nightly` and `all` workflows
=> Add release-1.2 branch and Istio compatibility test to nightly CI

deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
Fixes: https://github.com/istio/istio/issues/14327
This fix works for k8s v1.10+, cf. [Guaranteed Scheduling For Critical Add-On Pods](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#marking-pod-as-critical).
This is a partial fix for https://github.com/istio/istio/issues/14327 to only prevent race conditions with normal pods, by guaranteeing that the `istio-cni-node` pods [always start first on the nodes](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#effect-of-pod-priority-on-scheduling-order). There is still a race-condition with other CNI plugins on the node, e.g. Calico, which runs with the same priority.
=> Set priorityClassName on istio-cni-node

deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
These are using deprecated APIs that will be removed in k8s 1.16, which will release the same time we release istio 1.3
See istio/istio/issues/12211
=> Update to apps/v1

deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
This PR changes the RBAC API version to the current v1 (which is GA since I think 1.8: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.8.md#auth).
=> Make use of RBAC v1

deployments/kubernetes/install/helm/istio-cni/Chart.yaml
The release script rewrites the version and appVersion in
Chart.yaml but only when the current values are "1.1.0":
https://github.com/istio/istio/blob/37f66ed43167ae05b9889866f029bb5f33c92403/release/gcb/gcb_lib.sh#L188-L189
Updating the istio/cni Chart.yaml to use those magic values.
=> Update Helm version to magic tag to enable rewrite during release

Makefile.core.mk, Makefile.overrides.mk
- Rename some targets for consistent with other repos.
=> Enable the build container by default.

Makefile.overrides.mk
Currently prow-e2e doesn't work well with BUILD_WITH_CONTAINER=1
however, we are very close to having all make targts work with
BUILD_WITH_CONTAINER=1.
=> Place istio/cni on the BUILD_WITH_CONTAINER=1 plan

Makefile, Makefile.core.mk
Sadly a host mount must be used to share files between the build container
and the test case. The test case uses /tmp for this. This test case will
spew a bunch of backtraces, which it is supposed to spew.  The actual
test results pass.
=> Make `test` work properly

tools/packaging/common/iptables-retry.diff, tools/packaging/common/istio-iptables.sh
Pick up changes to `istio-iptables.sh` from `istio/istio:master`, esp. https://github.com/istio/istio/pull/17044 which removes cleanup code from the script.
I will cherry-pick this manually into `release-1.4` once https://github.com/istio/istio/pull/17989 is merged.
=> Sync istio-iptables.sh with istio/istio:master

deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml, deployments/kubernetes/install/helm/istio-cni/values.yaml, deployments/kubernetes/install/helm/istio-cni/values_gke.yaml
This PR allows to add custom annotations on the Pod level for the DaemonSet. This is beneficial to support use cases where for example custom validators or operators utilize annotations to  check if something should be allowed or not.
As a concrete example, we would like to be able to document that the pods as exceptionally getting broader access rights.
=> Allow to set custom annotations on pod level

deployments/kubernetes/install/scripts/install-cni.sh
This eliminates a race condition where CNI plugins and kubelet could read garbage when starting new pods while the CNI files are getting updated.
=> Make file modifications atomic in install-cni.sh

cmd/istio-cni/main_test.go
Set correct namespace in mock so that istio-init check is exercised
Issue: https://github.com/istio/istio/issues/18021
=> Fix TestCmdAddExcludePodWithIstioInitContainer unit test

cmd/istio-cni-repair/main.go, deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml, go.mod, pkg/repair/repair.go, pkg/repair/repair_test.go, pkg/repair/repair_test_helpers.go, pkg/repair/repaircontroller.go
There are some performance issues in large clusters with the poll-based repair controller. This switches it to a watch-based controller. Creating the PR for feedback and so we have something to track.
Todo:
[ ] Add more tests
[ ] Possibly swap the controller from a daemonset to a singleton controller, depending on performance
[ ] Fix event generation (does not currently work in watch-based daemon mode)
=> Watch-based repair controller

.gitignore
The new common build files require ignoring the `out/` directory, cf. https://github.com/istio/cni/pull/267.
=> Ignore out/ directory

tools/packaging/common/istio-iptables.sh
Some kernels, like COS on GKE, are configured without the 'xt_socket'
kernel module that implements the 'socket' match in iptables
rules. Replace the 'socket' match with a 'conntrack' state match that
diverts all established and related packets to the local stack.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
=> istio-iptables: Replace socket match with conntrack match

cmd/istio-cni/main.go, cmd/istio-cni/main_test.go, cmd/istio-cni/redirect.go
Signed-off-by: Yuchen Dai <silentdai@gmail.com>
The design since istio 1.3 is to capture all inbound traffic by default. 
Fix https://github.com/istio/istio/issues/22482
Also manual tested by apply a deployment with no container port and the expected rule `[2:120] -A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006` is hit twice
```
root@host-46:/home/ubuntu# ip netns exec "ebbb5767af2e" iptables-save -c
*nat
:PREROUTING ACCEPT [2450:147000]
:INPUT ACCEPT [2451:147060]
:OUTPUT ACCEPT [46:4064]
:POSTROUTING ACCEPT [47:4124]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
[2451:147060] -A PREROUTING -p tcp -j ISTIO_INBOUND
[6:360] -A OUTPUT -p tcp -j ISTIO_OUTPUT
[0:0] -A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
[2450:147000] -A …
```
=> fix inboundport annotation when it is empty

cmd/istio-cni/main.go, cmd/istio-cni/main_test.go, cmd/istio-cni/redirect.go
As workaround of #23038 
Simulate what non-cni template injector does on port 15090.
excludeInboundPorts is read only if includeInboundPorts is '*' so we can blindly add 15090 regardless if excludeInboundPorts is used
Should revert this PR when `podRedirectAnnot` is propagated to webhook along with https://github.com/istio/istio/pull/23037
=> Redirect: add 15090 to excludeInboundPorts 

cmd/istio-cni/main_test.go, cmd/istio-cni/redirect.go
Adding more ports to the default set of excluded ports set in https://github.com/istio/cni/pull/299.
Also added a helper function to deduplicate ports, since I don't know what the behavior would be if we have ports declared multiple times.
=> More default exlusion ports

tools/packaging/common/istio-iptables.sh
From `man hostname`:
```
-i, --ip-address
Display the IP address(es) of the host. Note that this works only if the host name can be resolved. Avoid using this option; use hostname --all-ip-addresses instead.
```
I've reworked the logic to use `--all-ip-addresses`, which shouldn't require a DNS query. Instead, we now loop across all IP addresses for the pod, and if we encounter one that is an ipv6 address, we enable ipv6 inbound rules.
This should fix https://github.com/istio/istio/issues/23770
=> Reworking ipv6 detection logic

deployments/kubernetes/Dockerfile.install-cni
Fixes https://github.com/istio/istio/issues/23643.
The `VOLUME` declaration causes all of `/opt` in the docker container to be mounted with `noexec`, which prevents the CNI repair binary from being executed.
=> Fixing cos_containerd mounting repair binary with noexec
